#!/bin/sh

rm -f config.* src/Makedeps src/Makevars \
    src/addressbook.pb.cc src/addressbook.pb.h \
    src/protobufrpc.pb.cc src/protobufrpc.pb.h \
    src/*.o src/*.d src/*.a src/*.dll src/*.so src/*.rc */*~ *~ \
    src/symbols.rds \
    vignettes/RProtoBuf*.aux vignettes/RProtoBuf*.log \
    vignettes/RProtoBuf*.out vignettes/RProtoBuf*.toc \
    vignettes/RProtoBuf*.tex vignettes/RProtoBuf*.pdf \
    vignettes/pinp.cls

rm -rf inst/doc/auto autom4te.cache


