// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TradeData.proto

#ifndef PROTOBUF_TradeData_2eproto__INCLUDED
#define PROTOBUF_TradeData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace TradeData {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_TradeData_2eproto();
void protobuf_AssignDesc_TradeData_2eproto();
void protobuf_ShutdownFile_TradeData_2eproto();

class Fill;
class Trades;

// ===================================================================

class Fill : public ::google::protobuf::Message {
 public:
  Fill();
  virtual ~Fill();
  
  Fill(const Fill& from);
  
  inline Fill& operator=(const Fill& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Fill& default_instance();
  
  void Swap(Fill* other);
  
  // implements Message ----------------------------------------------
  
  Fill* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Fill& from);
  void MergeFrom(const Fill& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required double timestamp = 1;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  inline double timestamp() const;
  inline void set_timestamp(double value);
  
  // required string symbol = 2;
  inline bool has_symbol() const;
  inline void clear_symbol();
  static const int kSymbolFieldNumber = 2;
  inline const ::std::string& symbol() const;
  inline void set_symbol(const ::std::string& value);
  inline void set_symbol(const char* value);
  inline void set_symbol(const char* value, size_t size);
  inline ::std::string* mutable_symbol();
  
  // required double price = 3;
  inline bool has_price() const;
  inline void clear_price();
  static const int kPriceFieldNumber = 3;
  inline double price() const;
  inline void set_price(double value);
  
  // required int32 size = 4;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 4;
  inline ::google::protobuf::int32 size() const;
  inline void set_size(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TradeData.Fill)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  double timestamp_;
  ::std::string* symbol_;
  static const ::std::string _default_symbol_;
  double price_;
  ::google::protobuf::int32 size_;
  friend void  protobuf_AddDesc_TradeData_2eproto();
  friend void protobuf_AssignDesc_TradeData_2eproto();
  friend void protobuf_ShutdownFile_TradeData_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Fill* default_instance_;
};
// -------------------------------------------------------------------

class Trades : public ::google::protobuf::Message {
 public:
  Trades();
  virtual ~Trades();
  
  Trades(const Trades& from);
  
  inline Trades& operator=(const Trades& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Trades& default_instance();
  
  void Swap(Trades* other);
  
  // implements Message ----------------------------------------------
  
  Trades* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Trades& from);
  void MergeFrom(const Trades& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .TradeData.Fill fill = 1;
  inline int fill_size() const;
  inline void clear_fill();
  static const int kFillFieldNumber = 1;
  inline const ::TradeData::Fill& fill(int index) const;
  inline ::TradeData::Fill* mutable_fill(int index);
  inline ::TradeData::Fill* add_fill();
  inline const ::google::protobuf::RepeatedPtrField< ::TradeData::Fill >&
      fill() const;
  inline ::google::protobuf::RepeatedPtrField< ::TradeData::Fill >*
      mutable_fill();
  
  // @@protoc_insertion_point(class_scope:TradeData.Trades)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::TradeData::Fill > fill_;
  friend void  protobuf_AddDesc_TradeData_2eproto();
  friend void protobuf_AssignDesc_TradeData_2eproto();
  friend void protobuf_ShutdownFile_TradeData_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Trades* default_instance_;
};
// ===================================================================


// ===================================================================

// Fill

// required double timestamp = 1;
inline bool Fill::has_timestamp() const {
  return _has_bit(0);
}
inline void Fill::clear_timestamp() {
  timestamp_ = 0;
  _clear_bit(0);
}
inline double Fill::timestamp() const {
  return timestamp_;
}
inline void Fill::set_timestamp(double value) {
  _set_bit(0);
  timestamp_ = value;
}

// required string symbol = 2;
inline bool Fill::has_symbol() const {
  return _has_bit(1);
}
inline void Fill::clear_symbol() {
  if (symbol_ != &_default_symbol_) {
    symbol_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& Fill::symbol() const {
  return *symbol_;
}
inline void Fill::set_symbol(const ::std::string& value) {
  _set_bit(1);
  if (symbol_ == &_default_symbol_) {
    symbol_ = new ::std::string;
  }
  symbol_->assign(value);
}
inline void Fill::set_symbol(const char* value) {
  _set_bit(1);
  if (symbol_ == &_default_symbol_) {
    symbol_ = new ::std::string;
  }
  symbol_->assign(value);
}
inline void Fill::set_symbol(const char* value, size_t size) {
  _set_bit(1);
  if (symbol_ == &_default_symbol_) {
    symbol_ = new ::std::string;
  }
  symbol_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Fill::mutable_symbol() {
  _set_bit(1);
  if (symbol_ == &_default_symbol_) {
    symbol_ = new ::std::string;
  }
  return symbol_;
}

// required double price = 3;
inline bool Fill::has_price() const {
  return _has_bit(2);
}
inline void Fill::clear_price() {
  price_ = 0;
  _clear_bit(2);
}
inline double Fill::price() const {
  return price_;
}
inline void Fill::set_price(double value) {
  _set_bit(2);
  price_ = value;
}

// required int32 size = 4;
inline bool Fill::has_size() const {
  return _has_bit(3);
}
inline void Fill::clear_size() {
  size_ = 0;
  _clear_bit(3);
}
inline ::google::protobuf::int32 Fill::size() const {
  return size_;
}
inline void Fill::set_size(::google::protobuf::int32 value) {
  _set_bit(3);
  size_ = value;
}

// -------------------------------------------------------------------

// Trades

// repeated .TradeData.Fill fill = 1;
inline int Trades::fill_size() const {
  return fill_.size();
}
inline void Trades::clear_fill() {
  fill_.Clear();
}
inline const ::TradeData::Fill& Trades::fill(int index) const {
  return fill_.Get(index);
}
inline ::TradeData::Fill* Trades::mutable_fill(int index) {
  return fill_.Mutable(index);
}
inline ::TradeData::Fill* Trades::add_fill() {
  return fill_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::TradeData::Fill >&
Trades::fill() const {
  return fill_;
}
inline ::google::protobuf::RepeatedPtrField< ::TradeData::Fill >*
Trades::mutable_fill() {
  return &fill_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace TradeData

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TradeData_2eproto__INCLUDED
